Задание 1.1
k0rnagg/TKI-141 pull request #2
Opened 2024-02-12 17:16 UTC by k0rnagg

2024-02-16 18:38 UTC, MarinaPaley requested changes

2024-02-16 18:38 UTC, MarinaPaley commented on task 1.1/main.c
> + * @brief ������� ������� ��������� �
Файл должен быть сохранен в кодировке `UTF-8`

2024-02-16 18:38 UTC, MarinaPaley commented on task 1.1/main.c
> +    double def_A(double x, double y, double z);
Стили программирования
[CamelCase](https://ru.wikipedia.org/wiki/CamelCase)
[snake_case](https://ru.wikipedia.org/wiki/Snake_case)

2024-02-18 15:23 UTC, k0rnagg reviewed
Изменена кодировка на UTF-8 и изменен стиль программирования.

2024-02-21 14:24 UTC, MarinaPaley approved these changes

2024-02-28 18:41 UTC, closed without merging